Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0cff7528ff583bf9a   # us-east-1 - N.Virginia
    us-west-1:
      AMI: ami-0d9858aa3c6322f73   # us-west-1 - N.California
    eu-west-1:
      AMI: ami-0d71ea30463e0ff8d   # EU-west-1 - Ireland
    ap-southeast-1:
      AMI: ami-0c802847a7dd848c0   # ap-southeast-1 - Singapore
    ap-southeast-2:
      AMI: ami-07620139298af599e   # ap-southeast-2 - Syndey
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: "Name"
          Value: !Join 
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0